### ISSUE TITLE
Unclear instructions in Python Reddit API Wrapper details

### ISSUE THREAD

**Issue by OGreeni** [LukaHietala/reddit-bot-docs#3]
In the second to last paragraph of this section, there are mentions of the `REDDIT_CLIEND_ID` and `REDDIT_CLIENT_SECRET` as highlighted in blue and orange, respectively. However, these do not seem to be highlighted on my page.
![image](https://user-images.githubusercontent.com/87455082/172506234-9363ba0f-0dd4-4efe-a315-9b5dd150134d.png)

**Comment by EdyDeveloper** [comment]
As you've shared this app's details you should delete it and create another one before using.
The string of letters and numbers next to your profile picture is your client ID and the "secret" is the client secret.

**Comment by OGreeni** [comment]
Yeah I figured that out eventually, but I feel like the docs could be improved as others might still be confused.

**Comment by EdyDeveloper** [comment]
Yea I definitely agree. I think it was an oversight because it talks about highlighted text but no image/text is there.
